import type { Experience } from "@/types/content";

// Source of truth: GitHub README (primary reference per project brief).
// All metrics below are quoted directly from the README's highlight tables.
export const experience: Experience[] = [
  {
    slug: "sat-japan",
    company: "SAT Japan",
    companyUrl: "https://satjapan.com",
    title: "SQA Engineer",
    employmentType: "Full-time",
    startDate: "2024-08",
    endDate: null,
    domain: [
      "Automotive E-commerce",
      "Vehicle Marketplace",
      "Live Auctions",
      "International Shipping",
      "Web & Mobile (Android & iOS)",
    ],
    overview:
      "SAT Japan is a product-based automotive e-commerce platform that enables customers and dealers worldwide to buy, sell, negotiate, and auction Japanese vehicles through web and mobile applications. The platform manages the complete customer journey from vehicle discovery to payment, international shipping, and order management.",
    metrics: [
      { label: "Bugs Reported", value: "900+" },
      { label: "Test Cases Designed & Executed", value: "500+" },
      { label: "Regression Test Suite", value: "200+" },
      { label: "Release Test Coverage", value: "90%+" },
      { label: "Business Modules Tested", value: "10+" },
      { label: "Automation Coverage", value: "5+ Core Modules" },
    ],
    responsibilities: [
      "Lead end-to-end quality assurance across core business modules, including Used Cars, New Cars, Auctions, Reservations, Negotiations, Search & Filters, Sell My Car, Checkout, Orders, International Shipping, Dealer Portal, Admin Panel, and Android & iOS mobile applications.",
      "Design, execute, and maintain 500+ test cases, including a regression suite of 200+ scenarios covering critical business workflows.",
      "Validate end-to-end business workflows spanning vehicle discovery, auction bidding, negotiations, checkout, payment, international shipping, and order completion.",
      "Perform REST API testing using Postman and validate backend data integrity through MySQL database verification.",
      "Develop and maintain a Playwright automation framework using Python and Pytest for high-priority regression scenarios, reducing manual regression effort by approximately 20%.",
      "Design and execute API performance and load tests using Apache JMeter to evaluate backend response times, scalability, stability, and reliability.",
      "Validate sprint releases and production hotfixes through targeted regression of critical business workflows before production deployment.",
      "Perform exploratory testing focused on edge cases, API failures, slow network conditions, invalid user inputs, and real-device scenarios to identify production-impacting issues.",
      "Collaborate with Product Managers, QA Leads, Backend, Frontend, and Mobile developers to validate business requirements, verify defect fixes, and ensure release readiness.",
    ],
    tools: [
      "Playwright",
      "Python",
      "Pytest",
      "Postman",
      "JMeter",
      "SQLyog",
      "Jira",
      "BrowserStack",
      "Git",
      "Figma",
      "Chrome DevTools",
    ],
    isFlagship: true,
  },
  {
    slug: "yolkar",
    company: "YolKar",
    companyUrl: "https://yolkar.com",
    title: "SQA Engineer",
    employmentType: "Part-time · Remote",
    startDate: "2026-04",
    endDate: null,
    domain: [
      "Ride-sharing",
      "Mobility Platform",
      "Intercity Carpooling",
      "Mobile Application",
    ],
    overview:
      "YolKar is a ride-sharing platform focused on intercity travel, allowing Car Owners to publish scheduled rides while Passengers discover and reserve available seats. The platform is designed as a scalable mobility ecosystem with future expansion into intra-city ride-hailing services.",
    metrics: [
      { label: "Test Cases Designed", value: "150+" },
      { label: "Bugs Reported", value: "40+" },
      { label: "APIs Validated", value: "20+" },
      { label: "MVP Functional Coverage", value: "90%+" },
    ],
    responsibilities: [
      "Own QA activities for the Scheduled Ride MVP from feature development through release readiness.",
      "Validate complete business workflows including Car Owner onboarding, Passenger registration, identity verification, ride publishing, ride discovery, seat booking, trip lifecycle, and notification flows.",
      "Perform REST API validation using Postman to verify authentication, ride management, booking, profile, and location services.",
      "Conduct API performance and load testing using Apache JMeter to assess application scalability before production deployment.",
      "Verify UI implementation against Figma designs across mobile devices to ensure consistency with product requirements.",
      "Identify business workflow gaps, usability issues, and edge cases during feature implementation, contributing to overall product quality.",
      "Collaborate directly with the Product Owner and development team to validate business requirements and newly implemented features throughout the development lifecycle.",
    ],
    tools: [
      "Postman",
      "JMeter",
      "MySQL",
      "Jira",
      "TestRail",
      "Figma",
      "BrowserStack",
      "Chrome DevTools",
    ],
    isFlagship: false,
  },
  {
    slug: "cross-solutions",
    company: "Cross Solutions",
    companyUrl: "https://www.saasguru.co/",
    title: "SQA Intern",
    employmentType: "Internship",
    startDate: "2024-05",
    endDate: "2024-07",
    domain: ["SaaS", "Cloud Certification", "E-learning Platform"],
    overview:
      "Contributed to the quality assurance of SaaSGuru, a cloud certification platform that provides expert-led learning content, practice exams, and mock exams for cloud certification preparation.",
    metrics: [],
    responsibilities: [
      "Tested core SaaS modules including Mock Exams, Course Library, user authentication, and exam management workflows.",
      "Designed and executed sprint-based test cases using Zephyr Scale under QA Lead supervision.",
      "Performed functional, regression, and exploratory testing across assigned product features.",
      "Validated REST APIs using Postman to verify exam retrieval, submission, and result processing.",
      "Performed SQL validation to confirm backend data consistency during feature verification.",
      "Logged, verified, and tracked defects using Jira throughout the software testing lifecycle.",
    ],
    tools: ["Postman", "Jira", "Zephyr Scale", "MySQL", "Chrome DevTools"],
    isFlagship: false,
  },
];
